// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfvxdckszcwbvdvybnmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmdnhkY2tzemN3YnZkdnlibm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTEzMzgsImV4cCI6MjA2NzM4NzMzOH0.c7bDawrLmwLOCl9aHD5pu-5rtUAZMRn5eLFiRVpyIzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});